"""Emit the phonological rule tables as C# source.

Both languages read the same data this way, so a rule can only be wrong
in both at once rather than in one of them quietly. The logic itself is
hand-written on each side; ParityTests checks the pair agrees.

One translation happens here: the table's replacements use Python's
backreference syntax and .NET wants dollars, so the two differ by
exactly this substitution and nothing else.

    python -m python.tools.export_rules_cs
"""

from __future__ import annotations


import sys
from pathlib import Path

from python.build.g2p.ko.rules_data import LINK, TABLE

PROJECT_ROOT = Path(__file__).resolve().parents[2]
OUT = (PROJECT_ROOT / "unity" / "Packages"
       / "com.domicube.phoneme-matching" / "Runtime" / "Korean"
       / "RulesData.cs")

HEADER = """// Generated by python/tools/export_rules_cs.py - do not edit by hand.
//
// The table g2pkk carries in table.csv and the linking pairs from its
// regular.py, so neither implementation can drift from the data. Only
// the backreference syntax differs: Python writes group one as a
// backslash, .NET as a dollar.

namespace DomiCube.PhonemeMatching.Korean
{
    internal static class RulesData
    {
        /// <summary>Coda + onset pattern, and its replacement.</summary>
        internal static readonly string[,] Table =
        {
"""


BACKSLASH = chr(92)


def to_dotnet(replacement: str) -> str:
    """Python backreferences to .NET ones, dollars escaped first."""
    out = replacement.replace("$", "$$")
    for digit in "123456789":
        out = out.replace(BACKSLASH + digit, "$" + digit)
    return out


def literal(s: str) -> str:
    escaped = s.replace(BACKSLASH, BACKSLASH * 2).replace('"', BACKSLASH + '"')
    return '"' + escaped + '"'


def main() -> int:
    parts = [HEADER]
    for pattern, repl in TABLE:
        parts.append(f"            {{ {literal(pattern)}, "
                     f"{literal(to_dotnet(repl))} }},\n")
    parts.append("""        };

        /// <summary>Plain string replacements, applied in order.</summary>
        internal static readonly string[,] Link =
        {
""")
    for a, b in LINK:
        parts.append(f"            {{ {literal(a)}, {literal(b)} }},\n")
    parts.append("""        };
    }
}
""")
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"OK: {OUT}  (table {len(TABLE)}, link {len(LINK)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
